#name: Publish Helm Charts
#
#on:
#  push:
#    branches:
#      - main
#    paths:
#      - 'helm/**'
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v2
#
#    - name: Setup Helm
#      uses: azure/setup-helm@v1
#
#    - name: Package Helm charts
#      run: |
#        mkdir -p ./docs
#        helm package ./helm/* --destination ./docs
#
#    - name: Create Helm repository index
#      run: |
#        helm repo index ./docs --url https://bralbral.github.io/helm/
#
#    - name: Deploy to GitHub Pages
#      uses: peaceiris/actions-gh-pages@v3
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        publish_dir: ./docs
