title: My GitHub Page
description: >-
  A simple and stylish page using GitHub Pages and Jekyll.
theme: minimal
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bralbral.github.io" # the base hostname & protocol for your site
