title: My Jekyll Site
description: A simple Jekyll site
baseurl: "/site" # важно для размещения в папке
url: "https://bralbral.github.io" # замените на ваш URL на GitHub Pages
theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
