title: bralbral.github.io
description: A simple and stylish page using GitHub Pages and Jekyll.
baseurl: ""
url: "https://bralbral.github.io"
source: site
# https://jekyll-themes.com/pages-themes/minimal
theme: minimal
